### ISSUE TITLE
Error rqt_gui application

### ISSUE THREAD

**Issue by OscarRamosRubio** [mit-acl/panther#2] opened 2021-04-16 16:31 UTC
Hello everyone,

I've been following the tutorial in the Readme.md. However, as con you can see in the attached image, I have some problems with the rqt_gui.  

I'm using ROS Noetic on Ubuntu 20.04. However the rqt_gui crashes. The error says: 

 TypeError: arguments did not match any overloaded call:
  QByteArray(): too many arguments
  QByteArray(int, str): argument 1 has unexpected type 'str'
  QByteArray(Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str'

I've tried to fix it by following the answer found in this link: https://answers.ros.org/question/365220/rqt_gui-error-in-perspective-manager-in-ros-noetic/ . Basically I have changed "QtCore.QByteArray('000000ff00000000fd00000001...00')" on the line number 436 by  "b'000000ff00000000fd00000001...00'" on the demo_interface.perspective document (https://github.com/mit-acl/panther/blob/master/panther/rqt_cfgs/demo_interface.perspective). However it does not solve the problem.

Any idea?

Thanks

![Panther_ERROR](https://user-images.githubusercontent.com/73934640/115053158-1ad51580-9edf-11eb-913c-b749bc386b93.png)

**Comment by jtorde** [comment] 2021-04-19 13:38
Hi @OscarRamosRubio,

I don't have access right now to a machine with ROS Noetic on Ubuntu 20.04 to try to reproduce your issue. I will try to have a look at this as soon as I do (I think it should be an easy fix though). 

As a quick workaround, you can publish in the service `/change_mode` directly. See details here: [https://github.com/mit-acl/faster/issues/27](https://github.com/mit-acl/faster/issues/27)

Hope this helps!

**Comment by StevenHong** [comment] 2021-05-13 04:01
I also had the same issue, and tried the solution in the link, but it didn't work for me either. Any other solutions?

**Comment by jtorde** [comment] 2021-11-04 22:49
Hi @OscarRamosRubio,

I have just changed it (see the last commit) to make it work in Ubuntu 20.04/ROS Noetic 

I am closing this for now, but feel free to reopen it in case you are still facing this issue

**Closed by jtorde** 2021-11-04 22:49 UTC

**Comment by qimao7213** [comment] 2024-12-03 03:24
Hi, you can just change "QtCore.QByteArray('000000..." to "QtCore.QByteArray(b'000000..." by adding a "b". It works for me.
